- name: "Add Ubuntu keyserver for installing mariadb"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "0xF1656F24C74CD1D8"
    state: present
- name: "Add sgdo apt-repo for installing mariadb"
  apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://mirror.biznetgio.com/mariadb/repo/10.4/ubuntu bionic main
    state: present
- name: "Add Ondřej Surý php repo"
  apt_repository:
    repo: ppa:ondrej/php
    state: present
- name: "Install package"
  apt:
    name: apache2,software-properties-common,mariadb-server,php7.1,libapache2-mod-php7.1,php7.1-cli,php7.1-common,php7.1-mbstring,php7.1-gd,php7.1-intl,php7.1-xml,php7.1-mysql,php7.1-mcrypt,php7.1-zip,php7.1-gettext
    state: present
    update_cache: true
- name: "Start apache service"
  service:
    name: apache2
    state: started
    enabled: yes
- name: "Start MariaDB service"
  service:
    name: mariadb
    state: started
    enabled: yes
- name: "enable apache rewrite module"
  apache2_module:
    state: present
    name: rewrite
- name: "Enable mysqli using phpenmod"
  shell: /usr/sbin/phpenmod mysqli
- name: "Restart apache service"
  service:
    name: apache2
    state: restarted
    enabled: yes